DROP TABLE IF EXISTS function_entity CASCADE ;
CREATE TABLE function_entity
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    function_text VARCHAR(255),
    CONSTRAINT pk_functionentity PRIMARY KEY (id)
);