CREATE TABLE IF NOT EXISTS function_entity
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    function_text VARCHAR(255),
    user_id       BIGINT,
    CONSTRAINT pk_functionentity PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_entity
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login       VARCHAR(255),
    password    VARCHAR(255),
    authorities VARCHAR(255),
    CONSTRAINT pk_userentity PRIMARY KEY (id)
);

ALTER TABLE user_entity
    ADD CONSTRAINT fk_user_entity_on_function_entity FOREIGN KEY (id) REFERENCES function_entity (user_id);